// nozicija aNalogovogo napametpa v kadpe bYP i free-zoNe faila-konii
//  (imja smotpi v ciklogpamme)
#define OPOZ_DAN  0 // opozNavatelnue daNNue (kadp byP)
#define NUM_KDR   0 // Nomep kadpa (free-zoNa)
#define TH        1 // temnepatypa NapyjNogo vozdyxa
#define HB        2 // visota bapometpicheskaja
#define HG        3 // visota geometpicheskaja
#define VP        4 // skopost npibopNaja
// zaNjato PK  5
#define VUx       6 // yglovaja skopost kpeNa
#define Az        7 // nepegpyzka bokovaja
// zaNjato PK  8
#define Ay        9 // nepegpyzka veptikalNaja
#define SV       10 // nolojeNie pylja vusotu
#define UK       11 // ygol kpeNa
#define UN       12 // ygol kypsa gipomagNitNogo
#define UT       13 // ygol taNgaja
#define UKd      14 // ygol kpeNa pezepvNui
#define ZK       15 // otkloNeNie ot PSZ (pavNosigNalNaja zoNa) kypsa
#define KN       16 // kalibpovka miNimyma
#define ZG       17 // otkloNeNie ot PSZ glissadu
// zaNjato IPK1 caNal 18
#define RDl      19 // nolojeNie PyD (pykojatka ynpavleN.dvigatelem) levogo dvigatelja
#define Nnl      20 // obopotu veNtiljatopa levogo dvigatelja
#define Nvl      21 // obopotu KVD (komnpessopa vusokogo davleNia) levogo dvigatelja
#define Tl       22 // temnepatypa gaza za typbiNoi levogo dvigatelja
#define RDs      23 // nolojeNie PyD spedNego dvigatelja
// zaNjato IPK2 caNal 24
#define Ay_2     25 // nepegpyzka veptikalNaja (2 onpos)
#define SV_2     26 // nolojeNie pylja vusotu  (2 onpos)
#define UK_2     27 // ygol kpeNa              (2 onpos)
#define Nns      28 // obopotu veNtiljatopa spedNego dvigatelja
#define Nvs      29 // obopotu KVD spedNego dvigatelja
#define Ts       30 // temnepatypa gaza za typbiNoi spedNego dvigatelja
#define RDp      31 // nolojeNie PyD npavogo dvigatelja
#define Nnp      32 // obopotu veNtiljatopa npavogo dvigatelja
#define Nvp      33 // obopotu KVD npavogo dvigatelja
#define Tp       34 // temnepatypa gaza za typbiNoi npavogo dvigatelja
#define BDl      35 // vibpacia levogo dvigatelja
#define BDs      36 // vibpacia spedNego dvigatelja
#define BDp      37 // vibpacia npavogo dvigatelja
// zaNjato dVP   --> 38
#define dVP      38 // npoizvodNaja npibopNoi skoposti
#define RB       39 // nolojeNie bapaNki shtypvala
// zaNjato dHG   --> 40
#define dHG      40 // npoizvodNaja vusotu geometpicheskoi
#define Ay_3     41 // nepegpyzka veptikalNaja (3 onpos)
#define SV_3     42 // nolojeNie pylja vusotu  (3 onpos)
#define UK_3     43 // ygol kpeNa              (3 onpos)
#define RP       44 // nolojeNie nedalei
#define RKL      45 // nolojeNie koloNki shtypvala
#define SE       46 // nolojeNie elepoNa
#define SN       47 // nolojeNie pylja NanpavleNija
#define KM       48 // kalibpovka maksimyma
#define SVS      49 // nolojeNie stabilizatopa
#define MZ       50 // nolojeNie zakpulka
// zaNjato IPK (sobutie) --> 51
// zaNjato HBotn --> 52
#define HBotn    52 // vusota bapometpicheskaja otNositelNaja
// zaNjato dMZ   --> 53
#define dMZ      53 // npoizvodNaja nolojeNija zakpulka
#define DKA      54 // nepenad davleNija kabiNa-atmosfepa
											// svobodNo	--> 55
// zaNjato V3    --> 56
#define V3       56 // miNimalNaja npibopnaja skopost ybopki zakpulkov
#define Ay_4     57 // nepegpyzka veptikalNaja (4 onpos)
#define SV_4     58 // nolojeNie pylja vusotu  (4 onpos)
#define UK_4     59 // ygol kpeNa              (4 onpos)
#define QS       60 // ves samoleta s tonlivom
#define MTV      61 // nolojeNie tpimmepa pylja vusotu
#define EA27     62 // NanpjajeNie 27B Na avapiNoi shiNe
#define QT       63 // ostatok tonliva symmapNui
