// apol_lim.h - gpaNicu atpibytov noleta
#define MIN_VES_VZLET    20.0	// vzletNui ves bez tonliva, t
#define MAX_VES_VZLET    40.0
#define MIN_SAX_VZLET    10.0 // SAX Na vzlete, %
#define MAX_SAX_VZLET    30.0
#define MIN_DAVLENIE    700	  // davleNie, mm.pt.st.
#define MAX_DAVLENIE    780
#define MIN_UN_Vnn        0   // ygol kypsa Vnn
#define MAX_UN_Vnn      360
#define MIN_L_Vnn      1000   // dliNa Vnn, m
#define MAX_L_Vnn		   4000
#define MIN_Hkp         300   // vusota kpyga, m
#define MAX_Hkp         900
#define MIN_Hep_POS     800   // vusota esheloNa nepexoda nosadka, m
#define MAX_Hep_POS    1500
#define MIN_Htvg			  300   // vusota tochki vhoda v glissady, m
#define MAX_Htvg        900
#define MIN_Ltvg		   4000   // passtojaNie ot topca Vnn do tochki vhoda v glissady, m
#define MAX_Ltvg      12000
#define MIN_Hbprm		 	   50   // vusota npoleta bnPM, m
#define MAX_Hbprm       100
#define MIN_Lbprm				800   // passtojaNie ot topca Vnn do bnPM, m
#define MAX_Lbprm      1500
#define MIN_Hdprm			  150   // vusota npoleta DnPM, m
#define MAX_Hdprm       300
#define MIN_Ldprm			 2000   // passtojaNie ot topca Vnn do DnPM, m
#define MAX_Ldprm      5000
#define MIN_Hvpr         20   // vusota npiNjatia pesheNia, m
#define MAX_Hvpr        100

