// opisanie poley cyclogrammy
#define CFLD_ID    0   // ideNtifikatop
#define CFLD_NM    1   // imya
#define CFLD_TP    2   // tin
#define CFLD_FO    3   // chastota pegistpacii
#define CFLD_CN    4   // kaNal onpos 1
#define CFLD_CN2   5   // kaNal onpos 2
#define CFLD_CN3   6   // kaNal onpos 3
#define CFLD_CN4   7   // kaNal onpos 4
#define CFLD_RZ    5   // pazpjad byP
#define CFLD_CNC   6   // kaNal PK fail-konia
#define CFLD_RZC   7   // pazpjad fail-konia
