// FK_lim.h - gpaNicu atpibutov faila-konii:      (13.01.13)
#define MIN_SS_FK            0    // gpanicu slova sostojaNija (obpabotki) faila-konii
#define MIN_SZ_KDR          24    // gpanicu pazmepa kadpa faila-konii (byte)
#define MAX_SZ_KDR         400
#define MIN_DL_BUR_KDR      24    // gpanicu dliNu zoNu kadpa-bYP faila-konii (iNfopmacioNNux slov)
#define MAX_DL_BUR_KDR     128
#define MIN_SZ_BUR_KDR      24    // gpanicu pazmepa zoNu kadp-bYP faila-konii (byte)
#define MAX_SZ_BUR_KDR     128
#define MIN_SZ_FREE_ZONE    48    // gpanicu pazmepa free-zoNu faila-konii (byte)
#define MAX_SZ_FREE_ZONE   400
#define MIN_DL_FK           60    // gpanicu dliNu faila-kopii (kadpov)
#define MAX_DL_FK         1000
#define MIN_SZ_SPB        1024    // gpanicu pazmepa synepbloka
#define MAX_SZ_SPB       20480

