// OD_lim.cpp - gpaNicu atpibytov onozNavatelNux daNNux
#define MIN_TIME       0	// vremja
#define MAX_HOUR      24  // chasu
#define MAX_MIN       60  // miNytu
#define MAX_SEC       60  // sekyNdu
#define MIN_DATE       1	// data
#define MAX_DATE      31  //
#define MIN_MONTH      1	// mesjac
#define MAX_MONTH     12	//
#define MIN_YEAR    1960	// god
#define MAX_YEAR    2013	//
#define MIN_REIS       1	// N peisa
#define MAX_REIS    9999	//
#define MIN_BORT       1	// N bopta
#define MAX_BORT   99999	//
