// onisaNie bitov slova sostojaNia faila-konii
#define AFK_INP        01  // atpibytu faila-konii (01)
#define OD_INP         02  // onozNavatelNue daNNue (03)
#define APOL_INP       04  // atpibytu noleta (07)
#define FRM_BP        010  // PK modificipovaNNue (017)
#define FIZ_AP        020  // An npeobpazovaNue iz koda v fiziky (037)
#define FRM_CP_1     0100  // sfopmipovaNu paschetNue An, npohod 1
#define FRM_CP_2     0200  // sfopmipovaNu paschetNue An, npohod 2
#define FRM_CP_3     0400  // sfopmipovaNu paschetNue An, npohod 3
#define FRM_IRK_1   01000  // sfopmipovaNu paschetNue PK, npohod 1
#define FRM_IRK_2   02000  // sfopmipovaNu paschetNue PK, npohod 2
#define FRM_IRK_3   04000  // sfopmipovaNu paschetNue PK, npohod 3
#define FRM_SB     010000  // sfopmipovaNu sobutija
