// var_glob.h - globalNue nepemeNNue
float         *mas_free_pi; // yKZT Na massiv An free-zoNu kadpa faila-konii
unsigned long *mas_free_rk; // yKZT Na massiv PK free-zoNu kadpa faila-konii
short         *mas_bur_pi;  // yKZT Na massiv daNNux zoNu kadp-bUR kadpa faila-konii

int d_fk,          // deskpintop faila-konii
		sst_fk,        // slovo sostojaNija (obpabotki) faila-konii
		dl_fk,         // dliNa faila-kopii (kadpov)
		dl_bur_kdr,    // dliNa zoNu kadpa-bYP faila-konii (iNfopmacioNNux slov)
		sz_kdr,        // pazmep kadpa faila-konii (byte)
		sz_bur_kdr,    // pazmep zoNu kadp-bYP faila-konii (byte)
		sz_free_zone,  // pazmep free-zoNu faila-konii (byte)
		sz_spb;        // pazmep synepbloka faila-konii (byte)
